version: "3.1"

services:
  mira:
    image: qlikea/mira
    ports:
      - "9100:9100"
    command: --mode local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  engine1:
    image: qlikea/engine:12.42.0
    ports:
      - "9176:9076"

  engine2:
    image: qlikea/engine:12.42.0
    ports:
      - "9276:9076"
