version: "3.1"

services:
  mira:
    image: qlikea/mira${TAG} # If TAG is not set docker image with tag 'latest' will be used.
    ports:
      - "9100:9100"
    command: --mode local
    environment:
     - MIRA_DISCOVERY_IDS=qix-engine, qix-engine-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  engine1:
    image: qlikea/engine:12.42.0
    ports:
      - "9176:9076"
    labels:
      mira-discovery-id: qix-engine

  engine2:
    image: qlikea/engine:12.42.0
    ports:
      - "9276:9076"
    labels:
      mira-discovery-id: qix-engine-dev
