version: "3.1"

services:
  mira:
    image: qlikea/mira
    ports:
      - "9100:9100"
    command: --mode local
    environment:
      - QIX_ENGINE_IMAGE_NAME=qlikea/engine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  engine1:
    image: qlikea/engine
    ports:
      - "9176:9076"

  engine2:
    image: qlikea/engine
    ports:
      - "9276:9076"
