version: "3.1"

services:
  mira:
    image: qlikea/mira${TAG} # If TAG is not set docker image with tag 'latest' will be used.
    ports:
      - "9100:9100"
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  qix-engine:
    image: qlikea/engine:community_version
    command: -S AcceptEULA=${ACCEPT_EULA}
    ports:
      - 9076:9076
    deploy:
      replicas: 2
    labels:
      qix-engine: ""
